server:
  port: ${SERVER_PORT:9001}
  servlet:
    context-path: /simba_auth

spring:
  application:
    name: simba-auth
  datasource:
    url: jdbc:mysql://10.50.30.178:13306/oc_extract?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: Lygr@0907
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 500
      max-lifetime: 18000000
      minimum-idle: 30
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: HiKariDataSource
      type: com.zaxxer.hikari.HikariDataSource
      idle-timeout: 180000
      auto-commit: true
  redis:
    url: 10.50.30.179
    username: admin
    password: lygr@0907
    port: 6379
