version: '3.9'
services:
  redis9001:
    image: 'redis:7.0.1'
    restart: always
    container_name: redis9001
    ports:
      - "9001:6379"
    command:
      - redis-server /etc/redis/redis.config
    volumes:
      - redis_data:/data
      - redis_logs:/logs
      - redis_config/redis.config:/etc/redis/redis.config
    environment:
      - TZ=Asia/Shanghai
    privileged: true

volumes:
  redis_data:
    external:
      name: redis_data
  redis_logs:
    external:
      name: redis_logs
  redis_config:
    external:
      name: redis_config